### ISSUE TITLE
pages branch: 'IViewComponentHelper' does not contain a definition for 'Invoke' and no extension method 'Invoke' accepting a first argument of type 'IViewComponentHelper'

### ISSUE THREAD

**Issue by spboyer** [bradygaster-zz/downr#16]
Error when running on non-windows

```
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
/Views/Shared/Post.cshtml(5,43): error CS1061: 'IViewComponentHelper' does not contain a definition for 'Invoke' and no extension method 'Invoke' accepting a first argument of type 'IViewComponentHelper' could be found (are you missing a using directive or an assembly reference?)
/Views/Shared/Post.cshtml(6,43): error CS1061: 'IViewComponentHelper' does not contain a definition for 'Invoke' and no extension method 'Invoke' accepting a first argument of type 'IViewComponentHelper' could be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
```

**Comment by spboyer** [comment]
Closing, #17 and #18 fixes.
